start: expr

expr: obj_expr

obj_expr: NEW this_id "(" constructor_params ")" ("." func_expr)*
| func_expr

func_expr: func_call
| inline_func
| this_id
inline_func: FUNC "(" inline_params ")" "{" "}"
func_call: this_id "(" func_params ")"
constructor_params: IDENTIFIER
func_params: IDENTIFIER
inline_params: ( "$" IDENTIFIER extension "<<" expr)*
extension: ":" all_types?
all_types: INT_TYPE
| STRING_TYPE
| CHAR_TYPE
| FLOAT_TYPE
| BOOL_TYPE


obj_id: obj_expr dot_id*
this_id: THIS dot_id*
| id
id: IDENTIFIER dot_id*
dot_id: "." IDENTIFIER

// tokens

IDENTIFIER: /[_a-zA-Z]\\w*/i
THIS: "this"
FUNC: "func"
NEW: "new"
INT_TYPE: /\\bint\\b/
STRING_TYPE: /\\bstr\\b/
CHAR_TYPE: /\\bchar\\b/
FLOAT_TYPE: /\\bfloat\\b/
BOOL_TYPE: /\\bbool\\b/

// imports

%import common.INT
%import common.WS
%ignore WS